### ISSUE TITLE
Error while querying pinot with Supersets.

### ISSUE THREAD

**Issue by SivaSamrajS** [betodealmeida/pinot-dbapi#1]
I have tried to integrate the Superset with Pinot. Integration was succesful. But while querying the data into Supersets against Presto. I am getting error.

`returned an error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/superset/sql_lab.py", line 182, in execute_sql
    db_engine_spec.execute(cursor, query.executed_sql, async_=True)
  File "/usr/lib/python3.6/site-packages/superset/db_engine_specs.py", line 385, in execute
    cursor.execute(query)
  File "/usr/lib/python3.6/site-packages/pinotdb-0.1.1-py3.6.egg/pinotdb/db.py", line 39, in g
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pinotdb-0.1.1-py3.6.egg/pinotdb/db.py", line 184, in execute
    raise exceptions.ProgrammingError(msg)
pinotdb.exceptions.ProgrammingError: Query`

**Comment by agrawaldevesh** [comment]
Hi ... I am working on this integration too and I have made a bunch of changes to superset and pinot to make this work. 

https://github.com/agrawaldevesh/incubator-superset and https://github.com/agrawaldevesh/pinot-dbapi are somewhat stale snapshots of my work. 

We are using this superset/pinot combo in production and its working okay. If there is interest, I am happy to work on pushing this to the respective trunks. 

But in the meanwhile, can you please give my fork a try and let me know how that works.

**Comment by SivaSamrajS** [comment]
Sure thanks will give try

**Comment by pckushan** [comment]
Hi, 
I have configured the pinotdb in superset database configurations, When trying the to test the connection it send the query incorrectly :( Can you kindly help in this. 

SQLAlchemy URI * : **pinot://192.168.1.41:9000/pql?server=http://192.168.1.41:9000/debug=true**

**1) ERROR:** 

INFO:root:Database.get_sqla_engine(). Masked URL: pinot://192.168.1.41:9000/pql?server=http://192.168.1.41:9000/debug=true
INFO:pinotdb.sqlalchemy:Updated pinot dialect args from {'dbapi': <module 'pinotdb' from '/usr/local/lib/python3.6/site-packages/pinotdb/__init__.py'>, 'debug': False}: None and False
INFO:pinotdb.sqlalchemy:Updated pinot dialect args from {'host': '192.168.1.41', 'port': 9000, 'path': 'pql', 'scheme': 'http', 'debug': False}: http://192.168.1.41:9000/debug=true and False
DEBUG:pinotdb.sqlalchemy:Query SELECT 1 has metrics, so rewriting its order-by/limit clauses to just top
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.41:9000
DEBUG:urllib3.connectionpool:http://192.168.1.41:9000 "POST /pql HTTP/1.1" 200 1402
ERROR:root:(pinotdb.exceptions.DatabaseError) Error when querying SELECT 1
TOP 100 from http://192.168.1.41:9000/pql, raw response is:
ProcessingException(errorCode:150, message:PQLParsingError:
org.apache.pinot.pql.parsers.Pql2CompilationException: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:66)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at org.apache.pinot.pql.parsers.PQL2Parser.selectStatement(PQL2Parser.java:262)
	at org.apache.pinot.pql.parsers.PQL2Parser.statement(PQL2Parser.java:185)
	at org.apache.pinot.pql.parsers.PQL2Parser.root(PQL2Parser.java:134)
	at org.apache.pinot.pql.parsers.Pql2Compiler.compileToBrokerRequest(Pql2Compiler.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.getQueryResponse(PqlQueryResource.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.post(PqlQueryResource.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124))
[SQL: SELECT 1
TOP 100]
(Background on this error at: http://sqlalche.me/e/4xp6)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pinotdb/db.py", line 224, in execute
    payload = r.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pinotdb/db.py", line 42, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pinotdb/db.py", line 226, in execute
    raise exceptions.DatabaseError(f"Error when querying {query} from {self.url}, raw response is:\n{r.text}") from e
pinotdb.exceptions.DatabaseError: Error when querying SELECT 1
TOP 100 from http://192.168.1.41:9000/pql, raw response is:
ProcessingException(errorCode:150, message:PQLParsingError:
org.apache.pinot.pql.parsers.Pql2CompilationException: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:66)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at org.apache.pinot.pql.parsers.PQL2Parser.selectStatement(PQL2Parser.java:262)
	at org.apache.pinot.pql.parsers.PQL2Parser.statement(PQL2Parser.java:185)
	at org.apache.pinot.pql.parsers.PQL2Parser.root(PQL2Parser.java:134)
	at org.apache.pinot.pql.parsers.Pql2Compiler.compileToBrokerRequest(Pql2Compiler.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.getQueryResponse(PqlQueryResource.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.post(PqlQueryResource.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/views/core.py", line 1375, in testconn
    conn.scalar(select([1]))
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 914, in scalar
    return self.execute(object_, *multiparams, **params).scalar()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/pinotdb/db.py", line 42, in g
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pinotdb/db.py", line 226, in execute
    raise exceptions.DatabaseError(f"Error when querying {query} from {self.url}, raw response is:\n{r.text}") from e
sqlalchemy.exc.DatabaseError: (pinotdb.exceptions.DatabaseError) Error when querying SELECT 1
TOP 100 from http://192.168.1.41:9000/pql, raw response is:
ProcessingException(errorCode:150, message:PQLParsingError:
org.apache.pinot.pql.parsers.Pql2CompilationException: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:66)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at org.apache.pinot.pql.parsers.PQL2Parser.selectStatement(PQL2Parser.java:262)
	at org.apache.pinot.pql.parsers.PQL2Parser.statement(PQL2Parser.java:185)
	at org.apache.pinot.pql.parsers.PQL2Parser.root(PQL2Parser.java:134)
	at org.apache.pinot.pql.parsers.Pql2Compiler.compileToBrokerRequest(Pql2Compiler.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.getQueryResponse(PqlQueryResource.java:110)
	at org.apache.pinot.controller.api.resources.PqlQueryResource.post(PqlQueryResource.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124))
[SQL: SELECT 1
TOP 100]
(Background on this error at: http://sqlalche.me/e/4xp6)
172.22.0.1 - - [29/Jan/2020 12:18:43] "POST /superset/testconn HTTP/1.1" 500 -
INFO:werkzeug:172.22.0.1 - - [29/Jan/2020 12:18:43] "POST /superset/testconn HTTP/1.1" 500 -

Resources :
I ran both the projects locally in my laptop. Following are the projects I used. 

****https://github.com/apache/incubator-superset**
**https://github.com/apache/incubator-pinot****
and also in the superset project I ran the Docker file updating the _requirement_ file to get **pinotdb==0.2.4**
This installed the pinotdb plugin.

**Comment by agrawaldevesh** [comment]
By "When trying the to test the connection it send the query incorrectly": Do you mean when you click the "Test Connection" in the Superset's add-database dialog ? Yeah. Well, PInot does not support "Select 1". So that "Test" isn't working. You might be better off connecting Superset to Pinot via Presto: Please see the presto-pinot connector in PrestoDB: https://prestodb.io/docs/current/connector/pinot.html. I am its author too and let me know if you have any issues. Feel free to create an issue on the prestodb's issues page: https://github.com/prestodb/presto/issues for the same.

**Comment by pckushan** [comment]
@agrawaldevesh  Thank you very much for the response :)  

**Do you mean when you click the "Test Connection" in the Superset's add-database dialog** YES
I tried to add the database to suerset. 
In the Superset documentation it mentions that "install the plugin by  _pip install pinotdb_" Thats why i connected like this. 

Meanwhile I tried to test the python library locally by following, (to test **Using SQLAlchemy** it gave an error mentioned below.) But **Using the DB API** its working. 
https://pypi.org/project/pinotdb/

it gives the following error 
-------------------------------------
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(select([func.count('*')], from_obj=places).scalar())
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 418, in scalar
    return self.execute(*multiparams, **params).scalar()
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 411, in execute
    return e._execute_clauseelement(self, multiparams, params)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2189, in _execute_clauseelement
    return connection._execute_clauseelement(elem, multiparams, params)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1092, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 468, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 474, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 589, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/kushan/.local/lib/python3.6/site-packages/pinotdb/sqlalchemy.py", line 28, in visit_select
    logger.debug(f'Query {select} has metrics, so rewriting its order-by/limit clauses to just top')
  File "/home/kushan/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 478, in __str__
    return str(self.compile())
-------------------------------------
1) Im I using the correct uri for pinot? 
2) What is the correct way of connecting the pinotdb to the superset ? 

Thanks.

**Comment by pckushan** [comment]
@agrawaldevesh Thank you 
I was able to connect to pinot via **presto**

**Comment by agrawaldevesh** [comment]
@pckushan, do you think this issue can be closed now ?
